/**
 * Build Script: Generate Config Files from Environment Variables
 * 
 * This script runs during Netlify deployment to create firebase-config.js
 * and cloudinary-config.js from environment variables.
 * 
 * Usage: Set environment variables in Netlify dashboard, then this script
 * generates the config files before the site is deployed.
 */

const fs = require('fs');
const path = require('path');

// Get environment variables
const FIREBASE_API_KEY = process.env.FIREBASE_API_KEY;
const FIREBASE_AUTH_DOMAIN = process.env.FIREBASE_AUTH_DOMAIN;
const FIREBASE_DATABASE_URL = process.env.FIREBASE_DATABASE_URL;
const FIREBASE_PROJECT_ID = process.env.FIREBASE_PROJECT_ID;
const FIREBASE_STORAGE_BUCKET = process.env.FIREBASE_STORAGE_BUCKET;
const FIREBASE_MESSAGING_SENDER_ID = process.env.FIREBASE_MESSAGING_SENDER_ID;
const FIREBASE_APP_ID = process.env.FIREBASE_APP_ID;

const CLOUDINARY_CLOUD_NAME = process.env.CLOUDINARY_CLOUD_NAME;
const CLOUDINARY_API_KEY = process.env.CLOUDINARY_API_KEY;
const CLOUDINARY_API_SECRET = process.env.CLOUDINARY_API_SECRET;
const CLOUDINARY_UPLOAD_PRESET = process.env.CLOUDINARY_UPLOAD_PRESET;

// Generate firebase-config.js
const firebaseConfig = `/**
 * Firebase Configuration Module
 * 
 * AUTO-GENERATED during build from environment variables.
 * DO NOT edit this file directly - changes will be overwritten.
 * 
 * @module firebase-config
 * @requires Firebase SDK v9+ (loaded via CDN)
 */

// Firebase configuration from environment variables
export const firebaseConfig = {
    apiKey: "${FIREBASE_API_KEY || ''}",
    authDomain: "${FIREBASE_AUTH_DOMAIN || ''}",
    databaseURL: "${FIREBASE_DATABASE_URL || ''}",
    projectId: "${FIREBASE_PROJECT_ID || ''}",
    storageBucket: "${FIREBASE_STORAGE_BUCKET || ''}",
    messagingSenderId: "${FIREBASE_MESSAGING_SENDER_ID || ''}",
    appId: "${FIREBASE_APP_ID || ''}"
};

// Flag to indicate if this is the real config or template
export const isFirebaseConfigured = ${FIREBASE_API_KEY ? 'true' : 'false'};

/**
 * Upload file to Firebase Storage
 * 
 * @async
 * @function uploadFile
 * @param {Object} storage - Firebase storage instance
 * @param {File} file - File to upload
 * @param {string} folder - Folder name (gallery, videos, posters)
 * @returns {Promise<string>} Download URL of uploaded file
 */
export async function uploadFile(file, folder = 'gallery') {
    try {
        const { ref, uploadBytes, getDownloadURL } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-storage.js');
        const { getStorage } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-storage.js');
        
        const storage = getStorage();
        
        // Create unique filename
        const timestamp = Date.now();
        const randomId = Math.random().toString(36).substring(7);
        const extension = file.name.split('.').pop();
        const filename = \`\${folder}/\${timestamp}_\${randomId}.\${extension}\`;
        
        // Create storage reference
        const storageRef = ref(storage, filename);
        
        // Upload file
        const snapshot = await uploadBytes(storageRef, file);
        
        // Get download URL
        const downloadURL = await getDownloadURL(snapshot.ref);
        
        return downloadURL;
    } catch (error) {
        console.error('Error uploading file to Firebase Storage:', error);
        throw new Error(\`Firebase upload failed: \${error.message}\`);
    }
}

/**
 * Delete file from Firebase Storage
 * 
 * @async
 * @function deleteFile
 * @param {string} fileURL - Full URL of the file to delete
 * @returns {Promise<void>}
 */
export async function deleteFile(fileURL) {
    try {
        const { ref, deleteObject } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-storage.js');
        const { getStorage } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-storage.js');
        
        const storage = getStorage();
        
        // Extract path from URL
        const urlParts = fileURL.split('/o/');
        if (urlParts.length < 2) {
            throw new Error('Invalid Firebase Storage URL');
        }
        
        const filePath = decodeURIComponent(urlParts[1].split('?')[0]);
        const fileRef = ref(storage, filePath);
        
        await deleteObject(fileRef);
    } catch (error) {
        console.error('Error deleting file from Firebase Storage:', error);
        throw new Error(\`Firebase delete failed: \${error.message}\`);
    }
}

/**
 * Initialize Firebase
 * 
 * @function initializeFirebase
 * @returns {Object} Firebase app instance
 */
export function initializeFirebase() {
    const { initializeApp } = require('https://www.gstatic.com/firebasejs/10.8.0/firebase-app.js');
    return initializeApp(firebaseConfig);
}

/**
 * Get Firebase Database instance
 * 
 * @function getDatabase
 * @returns {Object} Firebase database instance
 */
export function getDatabase() {
    const { getDatabase } = require('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
    return getDatabase();
}

/**
 * Gallery CRUD Operations
 */
export const GalleryCRUD = {
    async getAll() {
        const { ref, get, child } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        const snapshot = await get(ref(db, 'gallery'));
        return snapshot.exists() ? snapshot.val() : [];
    },
    
    async add(item) {
        const { ref, push, set } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        const newRef = push(ref(db, 'gallery'));
        await set(newRef, item);
        return newRef.key;
    },
    
    async update(id, data) {
        const { ref, update } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        await update(ref(db, \`gallery/\${id}\`), data);
    },
    
    async delete(id) {
        const { ref, remove } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        await remove(ref(db, \`gallery/\${id}\`));
    }
};

/**
 * Social Links CRUD Operations
 */
export const SocialLinksCRUD = {
    async getAll() {
        const { ref, get } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        const snapshot = await get(ref(db, 'socialLinks'));
        return snapshot.exists() ? snapshot.val() : {};
    },
    
    async update(data) {
        const { ref, set } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        await set(ref(db, 'socialLinks'), data);
    }
};

/**
 * Contact Messages CRUD Operations
 */
export const ContactCRUD = {
    async getAll() {
        const { ref, get } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        const snapshot = await get(ref(db, 'contactMessages'));
        return snapshot.exists() ? snapshot.val() : [];
    },
    
    async delete(id) {
        const { ref, remove } = await import('https://www.gstatic.com/firebasejs/10.8.0/firebase-database.js');
        const db = getDatabase();
        await remove(ref(db, \`contactMessages/\${id}\`));
    }
};
`;

// Generate cloudinary-config.js
const cloudinaryConfig = `/**
 * Cloudinary Configuration Module
 * 
 * AUTO-GENERATED during build from environment variables.
 * DO NOT edit this file directly - changes will be overwritten.
 * 
 * Handles Cloudinary uploads, transformations, and media management.
 * Replaces Firebase Storage with a simpler, more reliable solution.
 * 
 * @module cloudinary-config
 */

// Cloudinary Configuration from environment variables
export const cloudinaryConfig = {
    cloudName: '${CLOUDINARY_CLOUD_NAME || ''}',
    apiKey: '${CLOUDINARY_API_KEY || ''}',
    apiSecret: '${CLOUDINARY_API_SECRET || ''}',
    uploadPreset: '${CLOUDINARY_UPLOAD_PRESET || ''}'
};

/**
 * Upload file to Cloudinary
 * 
 * @async
 * @function uploadToCloudinary
 * @param {File} file - File to upload
 * @param {string} folder - Folder name (gallery, videos, posters)
 * @param {function} onProgress - Progress callback (optional)
 * @returns {Promise<string>} Secure URL of uploaded file
 * 
 * @example
 * const url = await uploadToCloudinary(file, 'gallery');
 */
export async function uploadToCloudinary(file, folder = 'gallery', onProgress = null) {
    try {
        // Create form data
        const formData = new FormData();
        formData.append('file', file);
        formData.append('upload_preset', cloudinaryConfig.uploadPreset);
        formData.append('folder', \`sfactor/\${folder}\`);
        
        // Optional: Add tags for organization
        const fileType = file.type.startsWith('video') ? 'video' : 'image';
        formData.append('tags', \`sfactor,\${fileType},\${folder}\`);
        
        // Upload to Cloudinary
        const uploadURL = \`https://api.cloudinary.com/v1_1/\${cloudinaryConfig.cloudName}/auto/upload\`;
        
        const xhr = new XMLHttpRequest();
        
        // Track upload progress
        if (onProgress) {
            xhr.upload.addEventListener('progress', (e) => {
                if (e.lengthComputable) {
                    const percentComplete = (e.loaded / e.total) * 100;
                    onProgress(percentComplete);
                }
            });
        }
        
        // Return promise
        return new Promise((resolve, reject) => {
            xhr.open('POST', uploadURL, true);
            
            xhr.onload = () => {
                if (xhr.status === 200) {
                    const response = JSON.parse(xhr.responseText);
                    resolve(response.secure_url);
                } else {
                    reject(new Error(\`Upload failed: \${xhr.statusText}\`));
                }
            };
            
            xhr.onerror = () => {
                reject(new Error('Network error during upload'));
            };
            
            xhr.send(formData);
        });
    } catch (error) {
        console.error('Error uploading to Cloudinary:', error);
        throw new Error(\`Cloudinary upload failed: \${error.message}\`);
    }
}

/**
 * Validate file before upload
 * 
 * @function validateFile
 * @param {File} file - File to validate
 * @param {Object} options - Validation options
 * @param {number} options.maxSize - Maximum file size in MB (default: 10)
 * @param {string[]} options.allowedTypes - Allowed MIME types
 * @returns {Object} Validation result { valid: boolean, error: string }
 */
export function validateFile(file, options = {}) {
    const {
        maxSize = 10, // MB
        allowedTypes = ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'video/mp4', 'video/webm']
    } = options;
    
    // Check file size
    const maxSizeBytes = maxSize * 1024 * 1024;
    if (file.size > maxSizeBytes) {
        return {
            valid: false,
            error: \`File size exceeds \${maxSize}MB limit\`
        };
    }
    
    // Check file type
    if (!allowedTypes.includes(file.type)) {
        return {
            valid: false,
            error: \`File type \${file.type} is not allowed\`
        };
    }
    
    return { valid: true, error: null };
}

/**
 * Get file type category
 * 
 * @function getFileType
 * @param {string} mimeType - MIME type of file
 * @returns {string} File type category (image, video, audio, other)
 */
export function getFileType(mimeType) {
    if (mimeType.startsWith('image/')) return 'image';
    if (mimeType.startsWith('video/')) return 'video';
    if (mimeType.startsWith('audio/')) return 'audio';
    return 'other';
}
`;

// Write files
const outputDir = path.resolve(__dirname);

try {
    fs.writeFileSync(path.join(outputDir, 'firebase-config.js'), firebaseConfig);
    console.log('✅ Generated firebase-config.js');
    
    fs.writeFileSync(path.join(outputDir, 'cloudinary-config.js'), cloudinaryConfig);
    console.log('✅ Generated cloudinary-config.js');
    
    console.log('\n🎉 Config files generated successfully!');
} catch (error) {
    console.error('❌ Error generating config files:', error.message);
    process.exit(1);
}
